### PR TITLE
chore: setValue ts interface support recur path

### PR DESCRIPTION
**Pull request by pointhalo**
[中文模板 / Chinese Template](https://github.com/DouyinFE/semi-design/blob/main/.github/PULL_REQUEST_TEMPLATE.zh-CN.md)

- [ ] I have read and followed [Pull Request Guidelines](https://github.com/DouyinFE/semi-design/blob/main/CONTRIBUTING-en-US.md#pull-request-guidelines) of the contributing guide.

### What kind of change does this PR introduce? (check at least one)

 - [ ] Bugfix
 - [ ] Feature
 - [ ] Code style update
 - [ ] Refactor
 - [ ] Test Case
 - [x] TypeScript definition update
 - [ ] Document improve
 - [ ] CI/CD improve
 - [ ] Branch sync
 - [ ] Other, please describe:

### PR description
#1737
#2243
实现如下类型提示，setValue 入参若为嵌套路径，对合法性进行校验。对不合法的key进行错误提示

image
image

### Changelog
🇨🇳 Chinese
- Chore: Form组件，FormApi setValue 类型定义更新，优化嵌套路径的提示 #1737 

---

🇺🇸 English
- Chore: FormApi setValue update interface define, optimizing nested paths #1737 

### Checklist
- [ ] Test or no need
- [ ] Document or no need
- [ ] Changelog or no need

### Other
- [ ] Skip Changelog

### CODE REVIEW

**Comment by pointhalo** [comment]
该PR不需要跟 v2.59 release。后续我单独发alpha给用户验证后再合入。

**Comment by pointhalo** [comment]
image
useFormApi还有一个类型问题，无法过编译

**Comment by pointhalo** [comment]
> image useFormApi还有一个类型问题，无法过编译

ignore解决，这里再给泛型做一轮体操的必要不是很大。

**Comment by rojer95** [comment]
image

貌似最新版不写泛型情况下，会变成这样。。。

**Comment by pointhalo** [comment]
> image
> 
> 貌似最新版不写泛型情况下，会变成这样。。。

get。本地测试没有考虑到。我再看下怎么改改（囧，类型体操还是略繁琐）

**Comment by pointhalo** [comment]
> image
> 
> 貌似最新版不写泛型情况下，会变成这样。。。

v2.59.1 已fix

**Pull request merged**
